<?php

namespace Kngbwsr\LaravelAgentOptimizer\Commands;

use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;

#[Signature('optimizeAgents:optimize {--root= : Root directory to scan (defaults to base_path())} {--min-lines= : Minimum section line count before extraction (overrides config line_threshold)} {--dry-run : Show what would be extracted without writing files}')]
#[Description('Extract long guideline sections from agent directive files into modular rule files')]
class AgentDirectiveOptimizeCommand extends Command
{
    /**
     * Section titles that are ALWAYS excluded from extraction, regardless of
     * config or line count. Merged with config('agent-optimizer.exceptions').
     *
     * @var array<int, string>
     */
    protected array $exceptions = [
        // 'example section title to always exclude',
    ];

    /**
     * Marker written immediately after "=== title ===" in the agent file once a
     * section has been extracted. Signals to subsequent runs that this section is
     * already optimized and must not be re-extracted. Also visible to LLMs so
     * they know the section content lives in separate directive files.
     */
    protected const OPTIMIZED_MARKER = '<!-- agent-optimized -->';

    /**
     * Default note prepended once to each source agent directive file (e.g. AGENTS.md,
     * CLAUDE.md) the first time any section in the file is extracted. Overridable via
     * config('agent-optimizer.agent_file_header').
     */
    protected const DEFAULT_AGENT_FILE_HEADER = "> **[agent-optimizer]** Some sections in this file are token-optimized. Their content has been extracted to separate directive files that are **loaded on demand** — only when the user's request is relevant to that section.\n\n---\n\n";

    /**
     * Default note prepended to every generated top-level rule file (_rule_*.md).
     * Not written to subsection files (_subsection_*.md). Overridable via
     * config('agent-optimizer.rule_file_header').
     */
    protected const DEFAULT_RULE_FILE_HEADER = "> **[agent-optimized]** This file is auto-generated by agent-optimizer.\n> Load any directive files referenced below **only when the user's request is relevant** to this section's content — do not load them by default.\n\n---\n\n";

    /**
     * Valid extraction strategy identifiers.
     *
     * @var array<int, string>
     */
    protected array $validStrategies = [
        'full_section',
        'nested_full',
        'nested_subsections',
        'nested_split',
        'auto',
    ];

    // -------------------------------------------------------------------------
    // Entry point
    // -------------------------------------------------------------------------

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $root = rtrim((string) ($this->option('root') ?: base_path()), DIRECTORY_SEPARATOR);

        // CLI --min-lines overrides config when explicitly provided.
        $minLines = $this->option('min-lines') !== null
          ? (int) $this->option('min-lines')
          : (int) config('agent-optimizer.line_threshold', 5);

        $dryRun = (bool) $this->option('dry-run');
        $basePath = trim((string) config('agent-optimizer.base_path', '.ai/rules'), '/\\');
        $rulesDir = $root.'/'.$basePath.'/agent-optimized';

        // Resolve agent files before preflight so we can detect which sections are
        // already optimized and protect their generated files from deletion.
        $files = $this->resolveAgentDirectiveFiles($root);
        $preserveSlugs = $this->collectOptimizedSlugs($files);

        $pruned = $this->pruneRulesDirectory($rulesDir, $dryRun, $preserveSlugs);

        // Ensure the output folder exists (may have been fully deleted, or may
        // never have existed yet). Skip when it already exists (smart-delete kept it).
        if (! $dryRun && ! is_dir($rulesDir)) {
            mkdir($rulesDir, 0755, true);
        }

        if ($pruned !== false) {
            if ($pruned === 'full') {
                $verb = $dryRun ? 'Would remove' : 'Removed';
                $this->line("<comment>Preflight:</comment> {$verb} the agent-optimized folder.");
            } elseif ($pruned === 'partial') {
                $verb = $dryRun ? 'Would clean' : 'Cleaned';
                $this->line("<comment>Preflight:</comment> {$verb} stale files from the agent-optimized folder.");
            }
            // 'none' — all files were preserved, no message needed.
            $this->newLine();
        }

        if (empty($files)) {
            $this->info('No agent directive files found.');

            return self::SUCCESS;
        }

        $this->line('<info>Agent files found:</info>');
        foreach ($files as $filePath) {
            $this->line('  '.basename($filePath));
        }
        $this->newLine();

        /** @var array<string, array{title: string, ruleFile: string, appliedTo: array<int, string>}> $extractions */
        $extractions = [];
        $writtenSlugs = [];

        foreach ($files as $filePath) {
            $this->processFile($filePath, $minLines, $rulesDir, $dryRun, $writtenSlugs, $extractions);
        }

        if (! empty($extractions)) {
            $this->line('<comment>Rules Directory:</comment> '.$basePath.'/agent-optimized');
            $this->newLine();
            $this->line('<info>Optimizations:</info>');
            foreach ($extractions as $entry) {
                $verb = $dryRun ? '[dry-run] Would extract' : 'Extracted';
                $this->line("  <comment>{$verb}:</comment> === {$entry['title']} ===");
                $this->line('  <comment>From:</comment> '.implode(', ', $entry['appliedTo']));
                $this->line("  <comment>Created:</comment> {$entry['ruleFile']}.\n");
            }
        } else {
            $this->info('No sections met the criteria for extraction.');
        }

        $count = count($extractions);

        if ($dryRun) {
            $this->info("Dry run: {$count} section(s) would be extracted.");
        } else {
            $this->info("Optimization complete. {$count} section(s) extracted from each of ".count($files).' file(s).');
        }

        return self::SUCCESS;
    }

    // -------------------------------------------------------------------------
    // Preflight housekeeping
    // -------------------------------------------------------------------------

    /**
     * Remove stale files from the agent-optimized folder before each run.
     *
     * When $preserveSlugs is empty (e.g. a fresh post-boost run where no markers
     * exist yet) the entire folder is deleted, matching the original behaviour.
     *
     * When $preserveSlugs is non-empty (standalone re-run where some sections are
     * already marked as optimized) only files / subdirectories whose name does
     * NOT correspond to a preserved slug are removed. This prevents deleting rule
     * files that are still referenced by already-optimized sections in the agent
     * directive files.
     *
     * Returns one of:
     *   'full'    — folder existed and was completely deleted
     *   'partial' — folder existed; only stale files were removed
     *   'none'    — folder existed but every file was preserved (nothing deleted)
     *   false     — folder did not exist; nothing to do
     *
     * @param  array<int, string>  $preserveSlugs
     * @return 'full'|'partial'|'none'|false
     */
    protected function pruneRulesDirectory(string $rulesDir, bool $dryRun, array $preserveSlugs = []): string|false
    {
        if (! is_dir($rulesDir)) {
            return false;
        }

        // ── Full delete when no optimized sections exist ──────────────────────────
        if (empty($preserveSlugs)) {
            if (! $dryRun) {
                $this->deleteDirectory($rulesDir);
            }

            return 'full';
        }

        // ── Smart delete: preserve files matching an optimized section slug ───────
        $rulePrefix = (string) config('agent-optimizer.rule_file_prefix', '_rule_');
        $ext = ltrim((string) config('agent-optimizer.rule_file_extension', 'md'), '.');
        $deletedAny = false;

        foreach (scandir($rulesDir) ?: [] as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }

            $path = $rulesDir.'/'.$item;
            $shouldPreserve = false;

            foreach ($preserveSlugs as $slug) {
                if ($item === $rulePrefix.$slug.'.'.$ext || $item === $rulePrefix.$slug) {
                    $shouldPreserve = true;
                    break;
                }
            }

            if (! $shouldPreserve) {
                $deletedAny = true;

                if (! $dryRun) {
                    is_dir($path) ? $this->deleteDirectory($path) : unlink($path);
                }
            }
        }

        return $deletedAny ? 'partial' : 'none';
    }

    /**
     * Recursively delete a directory and all of its contents.
     */
    protected function deleteDirectory(string $dir): void
    {
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($iterator as $item) {
            /** @var \SplFileInfo $item */
            $item->isDir() ? rmdir($item->getPathname()) : unlink($item->getPathname());
        }

        rmdir($dir);
    }

    // -------------------------------------------------------------------------
    // File discovery
    // -------------------------------------------------------------------------

    /**
     * Scan configured source directories for *.md files containing === sections.
     *
     * @return array<int, string>
     */
    protected function resolveAgentDirectiveFiles(string $root): array
    {
        /** @var array<int, string> $sourceDirs */
        $sourceDirs = config('agent-optimizer.source_directories', ['/']);
        $files = [];

        foreach ($sourceDirs as $dir) {
            $scanPath = rtrim($root.'/'.ltrim((string) $dir, '/\\'), '/\\');

            foreach (glob($scanPath.'/*.md') ?: [] as $path) {
                $content = file_get_contents($path);

                if ($content !== false && preg_match('/^=== .+ ===/m', $content)) {
                    $files[] = $path;
                }
            }
        }

        // Deduplicate in case source_directories entries overlap.
        return array_values(array_unique($files));
    }

    // -------------------------------------------------------------------------
    // File processing
    // -------------------------------------------------------------------------

    /**
     * Process a single agent directive file: parse sections, resolve strategy
     * per section, extract qualifying sections, and replace with placeholders.
     *
     * @param  array<string, bool>  $writtenSlugs
     * @param  array<string, array{title: string, ruleFile: string, appliedTo: array<int, string>}>  $extractions
     */
    protected function processFile(
        string $filePath,
        int $minLines,
        string $rulesDir,
        bool $dryRun,
        array &$writtenSlugs,
        array &$extractions
    ): void {
        $content = file_get_contents($filePath);

        if ($content === false) {
            $this->warn("Could not read: {$filePath}");

            return;
        }

        $workingContent = $this->extractBoostBlock($content);
        $hasWrapper = $workingContent !== $content;

        $sections = $this->parseSections($workingContent);
        $modified = $workingContent;
        $exceptions = $this->resolveExceptions();
        $filename = basename($filePath);

        foreach ($sections as $section) {
            $title = $section['title'];
            $body = $section['body'];
            $slug = $this->slugifyTitle($title);

            // Already extracted on a previous run — skip to avoid double-optimization.
            if ($section['is_optimized']) {
                continue;
            }

            if (in_array($title, $exceptions, true)) {
                continue;
            }

            if ($section['line_count'] <= $minLines) {
                continue;
            }

            $strategy = $this->resolveStrategy($title, $body);

            if ($strategy === 'full_section') {
                $modified = $this->applyFullSection(
                    $title,
                    $body,
                    $section['raw'],
                    $slug,
                    $strategy,
                    $rulesDir,
                    $dryRun,
                    $filename,
                    $writtenSlugs,
                    $extractions,
                    $modified
                );
            } else {
                $modified = $this->applyNestedStrategy(
                    $strategy,
                    $title,
                    $body,
                    $section['raw'],
                    $slug,
                    $rulesDir,
                    $dryRun,
                    $filename,
                    $writtenSlugs,
                    $extractions,
                    $modified
                );
            }
        }

        $sectionsChanged = $modified !== $workingContent;
        $hasAnyOptimizedSections = (bool) count(array_filter($sections, fn (array $s): bool => $s['is_optimized']));
        $agentFileHeader = $this->resolveAgentFileHeader();
        $headerAlreadyPresent = str_starts_with($content, $agentFileHeader);
        $shouldAddHeader = ($sectionsChanged || $hasAnyOptimizedSections) && ! $headerAlreadyPresent;

        if (! $dryRun && ($sectionsChanged || $shouldAddHeader)) {
            $newContent = $sectionsChanged
              ? ($hasWrapper
                ? (function () use ($content, $modified): string {
                    $tag = (string) config('agent-optimizer.boost_wrapper_tag', 'laravel-boost-guidelines');
                    $quotedTag = preg_quote($tag, '/');

                    return (string) preg_replace(
                        "/<{$quotedTag}>.*?<\\/{$quotedTag}>/s",
                        "<{$tag}>\n".rtrim($modified)."\n</{$tag}>",
                        $content
                    );
                })()
                : $modified)
              : $content;

            if ($shouldAddHeader) {
                $newContent = $agentFileHeader.$newContent;
            }

            file_put_contents($filePath, (string) $newContent);
        }
    }

    // -------------------------------------------------------------------------
    // Strategy: full_section
    // -------------------------------------------------------------------------

    /**
     * Extract an entire section body to a single flat rule file.
     *
     * @param  array<string, bool>  $writtenSlugs
     * @param  array<string, array{title: string, ruleFile: string, appliedTo: array<int, string>}>  $extractions
     */
    protected function applyFullSection(
        string $title,
        string $body,
        string $raw,
        string $slug,
        string $strategy,
        string $rulesDir,
        bool $dryRun,
        string $filename,
        array &$writtenSlugs,
        array &$extractions,
        string $modified
    ): string {
        $ruleFile = $this->ruleFileName($slug);
        $pretext = $this->resolvePretextLabel($strategy, 'section', $title);
        $placeholder = "=== {$title} ===\n".self::OPTIMIZED_MARKER."\n\n{$pretext} {$this->rulesFolder()}/{$ruleFile}\n";

        if (str_contains($modified, $placeholder)) {
            return $modified;
        }

        if ($dryRun) {
            if (! isset($writtenSlugs[$slug])) {
                $writtenSlugs[$slug] = true;
                $extractions[$slug] = ['title' => $title, 'ruleFile' => $ruleFile, 'appliedTo' => []];
            }
            $extractions[$slug]['appliedTo'][] = $filename;

            return $modified;
        }

        if (! isset($writtenSlugs[$slug])) {
            file_put_contents($rulesDir.'/'.$ruleFile, $this->resolveRuleFileHeader().$raw);
            $writtenSlugs[$slug] = true;
            $extractions[$slug] = ['title' => $title, 'ruleFile' => $ruleFile, 'appliedTo' => []];
        }

        $extractions[$slug]['appliedTo'][] = $filename;

        return str_replace($raw, $placeholder."\n", $modified);
    }

    // -------------------------------------------------------------------------
    // Strategy: nested variants
    // -------------------------------------------------------------------------

    /**
     * Dispatch nested strategy extraction based on the resolved strategy name.
     *
     * @param  array<string, bool>  $writtenSlugs
     * @param  array<string, array{title: string, ruleFile: string, appliedTo: array<int, string>}>  $extractions
     */
    protected function applyNestedStrategy(
        string $strategy,
        string $title,
        string $body,
        string $raw,
        string $slug,
        string $rulesDir,
        bool $dryRun,
        string $filename,
        array &$writtenSlugs,
        array &$extractions,
        string $modified
    ): string {
        $subHeaders = $this->parseMarkdownHeaders($body);
        $subThreshold = (int) config('agent-optimizer.subsection_line_threshold', 3);

        // Filter subsections that meet the subsection threshold.
        $qualifyingHeaders = array_values(array_filter(
            $subHeaders,
            fn (array $h): bool => $h['line_count'] >= $subThreshold
        ));

        // If no qualifying subsections exist, fall back to full_section.
        if (empty($qualifyingHeaders)) {
            return $this->applyFullSection(
                $title,
                $body,
                $raw,
                $slug,
                $strategy,
                $rulesDir,
                $dryRun,
                $filename,
                $writtenSlugs,
                $extractions,
                $modified
            );
        }

        return match ($strategy) {
            'nested_full' => $this->applyNestedFull(
                $title,
                $body,
                $raw,
                $slug,
                $rulesDir,
                $dryRun,
                $filename,
                $subHeaders,
                $qualifyingHeaders,
                $writtenSlugs,
                $extractions,
                $modified
            ),
            'nested_subsections' => $this->applyNestedSubsections(
                $title,
                $raw,
                $slug,
                $rulesDir,
                $dryRun,
                $filename,
                $subHeaders,
                $qualifyingHeaders,
                $writtenSlugs,
                $extractions,
                $modified,
                false
            ),
            'nested_split' => $this->applyNestedSubsections(
                $title,
                $raw,
                $slug,
                $rulesDir,
                $dryRun,
                $filename,
                $subHeaders,
                $qualifyingHeaders,
                $writtenSlugs,
                $extractions,
                $modified,
                true
            ),
            default => $this->applyFullSection(
                $title,
                $body,
                $raw,
                $slug,
                $strategy,
                $rulesDir,
                $dryRun,
                $filename,
                $writtenSlugs,
                $extractions,
                $modified
            ),
        };
    }

    /**
     * nested_full: Extract the full section. Write a master rule file at the
     * rules root and individual subsection files inside _rule_{slug}/.
     * Insert a single placeholder at the extraction site.
     *
     * @param  array<int, array{level: int, title: string, body: string, raw: string, line_count: int}>  $allHeaders
     * @param  array<int, array{level: int, title: string, body: string, raw: string, line_count: int}>  $qualifying
     * @param  array<string, bool>  $writtenSlugs
     * @param  array<string, array{title: string, ruleFile: string, appliedTo: array<int, string>}>  $extractions
     */
    protected function applyNestedFull(
        string $title,
        string $body,
        string $raw,
        string $slug,
        string $rulesDir,
        bool $dryRun,
        string $filename,
        array $allHeaders,
        array $qualifying,
        array &$writtenSlugs,
        array &$extractions,
        string $modified
    ): string {
        $masterFile = $this->ruleFileName($slug);
        $sectionPretext = $this->resolvePretextLabel('nested_full', 'section', $title);
        $subSectionPretext = $this->resolvePretextLabel('nested_full', 'sub_section');
        $placeholder = "=== {$title} ===\n".self::OPTIMIZED_MARKER."\n\n{$sectionPretext} {$this->rulesFolder()}/{$masterFile}\n";

        if (str_contains($modified, $placeholder)) {
            return $modified;
        }

        if ($dryRun) {
            if (! isset($writtenSlugs[$slug])) {
                $writtenSlugs[$slug] = true;
                $extractions[$slug] = ['title' => $title, 'ruleFile' => $masterFile, 'appliedTo' => []];
            }
            $extractions[$slug]['appliedTo'][] = $filename;

            return $modified;
        }

        if (! isset($writtenSlugs[$slug])) {
            $rulePrefix = (string) config('agent-optimizer.rule_file_prefix', '_rule_');
            $subDir = $rulesDir.'/'.$rulePrefix.$slug;

            if (! is_dir($subDir)) {
                mkdir($subDir, 0755, true);
            }

            $seniorLevel = $this->getSeniorHeaderLevel($allHeaders);
            $subsectionSlugs = [];

            // Write qualifying subsections to the subdirectory.
            foreach ($qualifying as $header) {
                $subSlug = $this->slugifyTitle($header['title']);
                $subFile = $subDir.'/'.$this->subsectionFileName($subSlug);
                file_put_contents($subFile, $header['raw']);
                $subsectionSlugs[$header['title']] = $subSlug;
            }

            // Build and write master file.
            $masterContent = $this->buildMasterContent(
                $title,
                $slug,
                $allHeaders,
                $qualifying,
                $seniorLevel,
                $subSectionPretext,
                $subsectionSlugs
            );
            file_put_contents($rulesDir.'/'.$masterFile, $this->resolveRuleFileHeader().$masterContent);

            $writtenSlugs[$slug] = true;
            $extractions[$slug] = ['title' => $title, 'ruleFile' => $masterFile, 'appliedTo' => []];
        }

        $extractions[$slug]['appliedTo'][] = $filename;

        return str_replace($raw, $placeholder."\n", $modified);
    }

    /**
     * nested_subsections / nested_split: Optionally extract the main body to
     * its own file (split=true) and always extract qualifying subsections to
     * _rule_{slug}/ with inline RULE references replacing each subsection.
     *
     * @param  array<int, array{level: int, title: string, body: string, raw: string, line_count: int}>  $allHeaders
     * @param  array<int, array{level: int, title: string, body: string, raw: string, line_count: int}>  $qualifying
     * @param  array<string, bool>  $writtenSlugs
     * @param  array<string, array{title: string, ruleFile: string, appliedTo: array<int, string>}>  $extractions
     */
    protected function applyNestedSubsections(
        string $title,
        string $raw,
        string $slug,
        string $rulesDir,
        bool $dryRun,
        string $filename,
        array $allHeaders,
        array $qualifying,
        array &$writtenSlugs,
        array &$extractions,
        string $modified,
        bool $splitMain
    ): string {
        $rulePrefix = (string) config('agent-optimizer.rule_file_prefix', '_rule_');
        $folder = $this->rulesFolder();

        // Dry-run: record one extraction entry per subsection.
        if ($dryRun) {
            foreach ($qualifying as $header) {
                $subSlug = $this->slugifyTitle($header['title']);
                $compositeSlug = $slug.'--'.$subSlug;
                $subFile = $rulePrefix.$slug.'/'.$this->subsectionFileName($subSlug);

                if (! isset($writtenSlugs[$compositeSlug])) {
                    $writtenSlugs[$compositeSlug] = true;
                    $extractions[$compositeSlug] = [
                        'title' => $title.' > '.$header['title'],
                        'ruleFile' => $subFile,
                        'appliedTo' => [],
                    ];
                }
                $extractions[$compositeSlug]['appliedTo'][] = $filename;
            }

            if ($splitMain) {
                $mainCompositeSlug = $slug.'--main';
                $mainFile = $this->ruleFileName($slug);

                if (! isset($writtenSlugs[$mainCompositeSlug])) {
                    $writtenSlugs[$mainCompositeSlug] = true;
                    $extractions[$mainCompositeSlug] = [
                        'title' => $title.' (main body)',
                        'ruleFile' => $mainFile,
                        'appliedTo' => [],
                    ];
                }
                $extractions[$mainCompositeSlug]['appliedTo'][] = $filename;
            }

            return $modified;
        }

        $subDir = $rulesDir.'/'.$rulePrefix.$slug;

        if (! is_dir($subDir)) {
            mkdir($subDir, 0755, true);
        }

        // Extract qualifying subsections and build inline replacements.
        $replacedRaw = $raw;
        $effectiveStrategy = $splitMain ? 'nested_split' : 'nested_subsections';
        $subSectionPretext = $this->resolvePretextLabel($effectiveStrategy, 'sub_section');

        foreach ($qualifying as $header) {
            $subSlug = $this->slugifyTitle($header['title']);
            $compositeSlug = $slug.'--'.$subSlug;
            $subFile = $rulePrefix.$slug.'/'.$this->subsectionFileName($subSlug);
            $headerPrefix = str_repeat('#', $header['level']);
            $resolvedSubPretext = str_replace('<title>', $this->sanitizeTitleForLabel($header['title']), $subSectionPretext);
            $subPlaceholder = "{$headerPrefix} {$header['title']}\n\n{$resolvedSubPretext} {$folder}/{$subFile}\n";

            if (! isset($writtenSlugs[$compositeSlug])) {
                file_put_contents($subDir.'/'.$this->subsectionFileName($subSlug), $header['raw']);
                $writtenSlugs[$compositeSlug] = true;
                $extractions[$compositeSlug] = [
                    'title' => $title.' > '.$header['title'],
                    'ruleFile' => $subFile,
                    'appliedTo' => [],
                ];
            }

            $extractions[$compositeSlug]['appliedTo'][] = $filename;

            // Replace the subsection's full raw block with an inline reference.
            $replacedRaw = str_replace($header['raw'], $subPlaceholder."\n", $replacedRaw);
        }

        // nested_split: also extract the main section body to its own rule file.
        if ($splitMain) {
            $mainCompositeSlug = $slug.'--main';
            $mainFile = $this->ruleFileName($slug);

            if (! isset($writtenSlugs[$mainCompositeSlug])) {
                // Write the modified section (subsections replaced by references) to the rule file.
                file_put_contents($rulesDir.'/'.$mainFile, $this->resolveRuleFileHeader().$replacedRaw);
                $writtenSlugs[$mainCompositeSlug] = true;
                $extractions[$mainCompositeSlug] = [
                    'title' => $title.' (main body)',
                    'ruleFile' => $mainFile,
                    'appliedTo' => [],
                ];
            }
            $extractions[$mainCompositeSlug]['appliedTo'][] = $filename;

            // Replace the entire original raw block with a single placeholder.
            $sectionPretext = $this->resolvePretextLabel('nested_split', 'section', $title);
            $masterPlaceholder = "=== {$title} ===\n".self::OPTIMIZED_MARKER."\n\n{$sectionPretext} {$folder}/{$mainFile}\n";

            return str_replace($raw, $masterPlaceholder."\n", $modified);
        }

        // nested_subsections: leave main header + direct body in-place, only
        // replace the subsection blocks with inline RULE references.
        // Inject the optimized marker right after the section title line so
        // subsequent runs can detect this section is already extracted.
        $firstNewline = strpos($replacedRaw, "\n");
        if ($firstNewline !== false) {
            $replacedRaw = substr($replacedRaw, 0, $firstNewline + 1)
                         .self::OPTIMIZED_MARKER."\n"
                         .substr($replacedRaw, $firstNewline + 1);
        }

        return str_replace($raw, $replacedRaw, $modified);
    }

    // -------------------------------------------------------------------------
    // Master file builder
    // -------------------------------------------------------------------------

    /**
     * Build the master index file content for a nested_full extraction.
     *
     * The most senior (lowest # level) header content is included verbatim.
     * All other headers become index entries linking to their subsection files.
     * If all headers share the same level, the master is a pure index.
     *
     * @param  array<int, array{level: int, title: string, body: string, raw: string, line_count: int}>  $allHeaders
     * @param  array<int, array{level: int, title: string, body: string, raw: string, line_count: int}>  $qualifying
     * @param  array<string, string>  $subsectionSlugs  title => slug
     */
    protected function buildMasterContent(
        string $sectionTitle,
        string $slug,
        array $allHeaders,
        array $qualifying,
        int $seniorLevel,
        string $subSectionPretext,
        array $subsectionSlugs
    ): string {
        $qualifyingTitles = array_column($qualifying, 'title');
        $lines = ["# {$sectionTitle}", ''];

        // Determine if any senior-level header has meaningful body content.
        $hasSeniorContent = false;

        foreach ($allHeaders as $header) {
            if ($header['level'] === $seniorLevel && trim($header['body']) !== '') {
                $hasSeniorContent = true;
                break;
            }
        }

        foreach ($allHeaders as $header) {
            $isSenior = $header['level'] === $seniorLevel;
            $isQualifying = in_array($header['title'], $qualifyingTitles, true);

            if ($isSenior && $hasSeniorContent) {
                // Include senior-level content verbatim.
                $lines[] = $header['raw'];
            } elseif ($isQualifying && isset($subsectionSlugs[$header['title']])) {
                $subSlug = $subsectionSlugs[$header['title']];
                $headerPrefix = str_repeat('#', $header['level']);
                $rulePrefix = (string) config('agent-optimizer.rule_file_prefix', '_rule_');
                $subRef = $this->rulesFolder().'/'.$rulePrefix.$slug.'/'.$this->subsectionFileName($subSlug);
                $lines[] = "{$headerPrefix} {$header['title']}";
                $lines[] = '';
                $resolvedPretext = str_replace('<title>', $this->sanitizeTitleForLabel($header['title']), $subSectionPretext);
                $lines[] = "{$resolvedPretext} {$subRef}";
                $lines[] = '';
            } else {
                // Non-qualifying header: include raw content as-is.
                $lines[] = $header['raw'];
            }
        }

        return implode("\n", $lines);
    }

    // -------------------------------------------------------------------------
    // Markdown header parser
    // -------------------------------------------------------------------------

    /**
     * Parse Markdown headers (# through ######) from a section body.
     * Returns each header with its title, level, body content, and line count.
     *
     * @return array<int, array{level: int, title: string, body: string, raw: string, line_count: int}>
     */
    protected function parseMarkdownHeaders(string $body): array
    {
        $pattern = '/^(#{1,6})\s+(.+?)\s*$\n?(.*?)(?=^#{1,6}\s|\z)/ms';
        preg_match_all($pattern, $body, $matches, PREG_SET_ORDER);

        $headers = [];

        foreach ($matches as $match) {
            $level = strlen($match[1]);
            $title = trim($match[2]);
            $content = $match[3];
            $raw = $match[0];
            $lineCount = substr_count(rtrim($content), "\n") + 1;

            $headers[] = [
                'level' => $level,
                'title' => $title,
                'body' => $content,
                'raw' => $raw,
                'line_count' => $lineCount,
            ];
        }

        return $headers;
    }

    /**
     * Return the most senior (lowest numeric level) header level from a set.
     *
     * @param  array<int, array{level: int, title: string, body: string, raw: string, line_count: int}>  $headers
     */
    protected function getSeniorHeaderLevel(array $headers): int
    {
        if (empty($headers)) {
            return 1;
        }

        return min(array_column($headers, 'level'));
    }

    // -------------------------------------------------------------------------
    // Strategy resolution
    // -------------------------------------------------------------------------

    /**
     * Determine the extraction strategy for a given section.
     *
     * Resolution order:
     *   1. config section_overrides keyed by raw section title
     *   2. global config extraction_strategy
     *   3. 'auto' is resolved here: inspect body for headers, return full_section or nested_full
     */
    protected function resolveStrategy(string $title, string $body): string
    {
        /** @var array<string, string> $overrides */
        $overrides = config('agent-optimizer.section_overrides', []);

        $strategy = $overrides[$title]
          ?? (string) config('agent-optimizer.extraction_strategy', 'full_section');

        if (! in_array($strategy, $this->validStrategies, true)) {
            $strategy = 'full_section';
        }

        if ($strategy === 'auto') {
            $headers = $this->parseMarkdownHeaders($body);

            if (empty($headers)) {
                $strategy = 'full_section';
            } else {
                $nested = (string) config('agent-optimizer.auto_nested_strategy', 'nested_full');
                $validNested = ['nested_full', 'nested_subsections', 'nested_split'];
                $strategy = in_array($nested, $validNested, true) ? $nested : 'nested_full';
            }
        }

        return $strategy;
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Return only the content inside <laravel-boost-guidelines> if the wrapper
     * exists, otherwise return the full content unchanged.
     */
    protected function extractBoostBlock(string $content): string
    {
        $tag = (string) config('agent-optimizer.boost_wrapper_tag', 'laravel-boost-guidelines');
        $quotedTag = preg_quote($tag, '/');

        if (preg_match("/<{$quotedTag}>(.*?)<\\/{$quotedTag}>/s", $content, $matches)) {
            return $matches[1];
        }

        return $content;
    }

    /**
     * Parse the content into sections keyed by === title === boundaries.
     *
     * @return array<int, array{title: string, body: string, raw: string, line_count: int}>
     */
    protected function parseSections(string $content): array
    {
        $pattern = '/^(=== (.+?) ===\s*\n)(.*?)(?=^=== .+ ===|\z)/ms';
        preg_match_all($pattern, $content, $matches, PREG_SET_ORDER);

        $sections = [];

        foreach ($matches as $match) {
            $titleHeader = $match[1];
            $title = trim($match[2]);
            $body = $match[3];
            $raw = $titleHeader.$body;
            $lineCount = substr_count(rtrim($body), "\n");

            // A section is already optimized when the optimized marker appears
            // immediately on the first line of the body (right after the title line).
            $isOptimized = str_starts_with($body, self::OPTIMIZED_MARKER."\n");

            $sections[] = [
                'title' => $title,
                'body' => $body,
                'raw' => $raw,
                'line_count' => $lineCount,
                'is_optimized' => $isOptimized,
            ];
        }

        return $sections;
    }

    /**
     * Merge class-level exceptions with any defined in config('agent-optimizer.exceptions').
     *
     * @return array<int, string>
     */
    protected function resolveExceptions(): array
    {
        return array_merge(
            $this->exceptions,
            config('agent-optimizer.exceptions', [])
        );
    }

    /**
     * Scan agent files for sections that already carry the optimized marker and
     * return their slugs. Used by pruneRulesDirectory() to decide which generated
     * files must be preserved during the preflight step.
     *
     * @param  array<int, string>  $files
     * @return array<int, string>
     */
    protected function collectOptimizedSlugs(array $files): array
    {
        $slugs = [];

        foreach ($files as $filePath) {
            $content = file_get_contents($filePath);

            if ($content === false) {
                continue;
            }

            $workingContent = $this->extractBoostBlock($content);

            foreach ($this->parseSections($workingContent) as $section) {
                if ($section['is_optimized']) {
                    $slugs[] = $this->slugifyTitle($section['title']);
                }
            }
        }

        return array_values(array_unique($slugs));
    }

    /**
     * Resolve the header note prepended to source agent directive files.
     * Returns config('agent-optimizer.agent_file_header') when set, otherwise
     * falls back to the built-in DEFAULT_AGENT_FILE_HEADER constant.
     */
    protected function resolveAgentFileHeader(): string
    {
        $configured = config('agent-optimizer.agent_file_header');

        return $configured !== null ? (string) $configured : self::DEFAULT_AGENT_FILE_HEADER;
    }

    /**
     * Resolve the header note prepended to top-level rule files (_rule_*.md).
     * Subsection files (_subsection_*.md) do not receive this header.
     * Returns config('agent-optimizer.rule_file_header') when set, otherwise
     * falls back to the built-in DEFAULT_RULE_FILE_HEADER constant.
     */
    protected function resolveRuleFileHeader(): string
    {
        $configured = config('agent-optimizer.rule_file_header');

        return $configured !== null ? (string) $configured : self::DEFAULT_RULE_FILE_HEADER;
    }

    /**
     * Resolve the pretext label for a RULE reference line.
     *
     * Checks config('agent-optimizer.reference_pretext') in this order:
     *   1. strategies.{$strategy}.{$type}  (when non-null)
     *   2. defaults.{$type}
     *   3. Hard-coded fallback '**RULE:**'
     *
     * @param  string  $strategy  e.g. 'full_section', 'nested_subsections'
     * @param  string  $type  'section' or 'sub_section'
     */
    protected function resolvePretextLabel(string $strategy, string $type, string $title = ''): string
    {
        /** @var array{defaults: array<string,string>, strategies: array<string,mixed>} $cfg */
        $cfg = config('agent-optimizer.reference_pretext', []);
        $default = $cfg['defaults'][$type] ?? '**RULE:**';

        $strategyEntry = $cfg['strategies'][$strategy] ?? null;

        if (is_array($strategyEntry)) {
            $label = isset($strategyEntry[$type]) && $strategyEntry[$type] !== null
              ? (string) $strategyEntry[$type]
              : $default;
        } else {
            // null or missing strategy entry → use default
            $label = $default;
        }

        return $title !== '' ? str_replace('<title>', $this->sanitizeTitleForLabel($title), $label) : $label;
    }

    /**
     * Return the rules folder path (relative to project root) used in
     * placeholder reference lines. Strips surrounding slashes so it can safely
     * be concatenated with a leading '/'.
     */
    protected function rulesFolder(): string
    {
        return trim((string) config('agent-optimizer.base_path', '.ai/rules'), '/\\').'/agent-optimized';
    }

    /**
     * Build the filename for a top-level rule file using the configured prefix
     * and extension, e.g. _rule_my-section.md.
     */
    protected function ruleFileName(string $slug): string
    {
        $prefix = (string) config('agent-optimizer.rule_file_prefix', '_rule_');
        $ext = ltrim((string) config('agent-optimizer.rule_file_extension', 'md'), '.');

        return $prefix.$slug.'.'.$ext;
    }

    /**
     * Build the filename for a subsection file using the configured prefix and
     * extension, e.g. _subsection_my-header.md.
     */
    protected function subsectionFileName(string $slug): string
    {
        $prefix = (string) config('agent-optimizer.subsection_file_prefix', '_subsection_');
        $ext = ltrim((string) config('agent-optimizer.rule_file_extension', 'md'), '.');

        return $prefix.$slug.'.'.$ext;
    }

    /**
     * Strip trailing " rules" (case-insensitive) from a title and trim
     * whitespace before substituting it into a <title> placeholder.
     */
    protected function sanitizeTitleForLabel(string $title): string
    {
        return trim((string) preg_replace('/\s+rules\s*$/i', '', $title));
    }

    /**
     * Convert a section title to a filesystem-safe slug.
     */
    protected function slugifyTitle(string $title): string
    {
        $slug = strtolower($title);
        $slug = preg_replace('/[^a-z0-9]+/', '-', $slug) ?? $slug;

        return trim($slug, '-');
    }
}
